name: Test

on: push

jobs:
 test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies and setuptools (required to build GLib)
        run: pip install --upgrade pip conan setuptools

      - run: conan --version
      - run: conan config install .github/conan

      - run: conan install recipes/glib/all/conanfile.py --version 2.78.3 --build missing

      - run: conan create recipes/glib/all/conanfile.py --version 2.78.3

      - run: conan cache check-integrity glib
 workaround:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies and setuptools (required to build GLib)
        run: pip install --upgrade pip conan setuptools

      - run: conan --version
      - run: conan config install .github/conan

      - run: conan install recipes/glib/all/conanfile.py --version 2.78.3 --build missing

      - run: conan create recipes/glib/all/conanfile.py --version 2.78.3
        env:
          # __pycache__ issue workaround
          PYTHONDONTWRITEBYTECODE: 1

      - run: find ~/.conan2 -type d -name __pycache__

      - run: conan cache check-integrity glib
